#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class contactDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertcontact(contact instance);
  partial void Updatecontact(contact instance);
  partial void Deletecontact(contact instance);
  #endregion
	
	public contactDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public contactDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public contactDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public contactDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public contactDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<contact> contacts
	{
		get
		{
			return this.GetTable<contact>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.contact")]
public partial class contact : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cid;
	
	private string _cname;
	
	private string _cemail;
	
	private string _cmsg;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncidChanging(int value);
    partial void OncidChanged();
    partial void OncnameChanging(string value);
    partial void OncnameChanged();
    partial void OncemailChanging(string value);
    partial void OncemailChanged();
    partial void OncmsgChanging(string value);
    partial void OncmsgChanged();
    #endregion
	
	public contact()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int cid
	{
		get
		{
			return this._cid;
		}
		set
		{
			if ((this._cid != value))
			{
				this.OncidChanging(value);
				this.SendPropertyChanging();
				this._cid = value;
				this.SendPropertyChanged("cid");
				this.OncidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="NVarChar(50)")]
	public string cname
	{
		get
		{
			return this._cname;
		}
		set
		{
			if ((this._cname != value))
			{
				this.OncnameChanging(value);
				this.SendPropertyChanging();
				this._cname = value;
				this.SendPropertyChanged("cname");
				this.OncnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cemail", DbType="NVarChar(50)")]
	public string cemail
	{
		get
		{
			return this._cemail;
		}
		set
		{
			if ((this._cemail != value))
			{
				this.OncemailChanging(value);
				this.SendPropertyChanging();
				this._cemail = value;
				this.SendPropertyChanged("cemail");
				this.OncemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmsg", DbType="NVarChar(50)")]
	public string cmsg
	{
		get
		{
			return this._cmsg;
		}
		set
		{
			if ((this._cmsg != value))
			{
				this.OncmsgChanging(value);
				this.SendPropertyChanging();
				this._cmsg = value;
				this.SendPropertyChanged("cmsg");
				this.OncmsgChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
