#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class couponDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertcoupon(coupon instance);
  partial void Updatecoupon(coupon instance);
  partial void Deletecoupon(coupon instance);
  #endregion
	
	public couponDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public couponDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public couponDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public couponDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public couponDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<coupon> coupons
	{
		get
		{
			return this.GetTable<coupon>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.coupon")]
public partial class coupon : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cid;
	
	private string _c_code;
	
	private System.Nullable<int> _discount;
	
	private System.Nullable<int> _max_discount;
	
	private string _last_date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncidChanging(int value);
    partial void OncidChanged();
    partial void Onc_codeChanging(string value);
    partial void Onc_codeChanged();
    partial void OndiscountChanging(System.Nullable<int> value);
    partial void OndiscountChanged();
    partial void Onmax_discountChanging(System.Nullable<int> value);
    partial void Onmax_discountChanged();
    partial void Onlast_dateChanging(string value);
    partial void Onlast_dateChanged();
    #endregion
	
	public coupon()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int cid
	{
		get
		{
			return this._cid;
		}
		set
		{
			if ((this._cid != value))
			{
				this.OncidChanging(value);
				this.SendPropertyChanging();
				this._cid = value;
				this.SendPropertyChanged("cid");
				this.OncidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_code", DbType="NVarChar(50)")]
	public string c_code
	{
		get
		{
			return this._c_code;
		}
		set
		{
			if ((this._c_code != value))
			{
				this.Onc_codeChanging(value);
				this.SendPropertyChanging();
				this._c_code = value;
				this.SendPropertyChanged("c_code");
				this.Onc_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Int")]
	public System.Nullable<int> discount
	{
		get
		{
			return this._discount;
		}
		set
		{
			if ((this._discount != value))
			{
				this.OndiscountChanging(value);
				this.SendPropertyChanging();
				this._discount = value;
				this.SendPropertyChanged("discount");
				this.OndiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_discount", DbType="Int")]
	public System.Nullable<int> max_discount
	{
		get
		{
			return this._max_discount;
		}
		set
		{
			if ((this._max_discount != value))
			{
				this.Onmax_discountChanging(value);
				this.SendPropertyChanging();
				this._max_discount = value;
				this.SendPropertyChanged("max_discount");
				this.Onmax_discountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_date", DbType="NVarChar(50)")]
	public string last_date
	{
		get
		{
			return this._last_date;
		}
		set
		{
			if ((this._last_date != value))
			{
				this.Onlast_dateChanging(value);
				this.SendPropertyChanging();
				this._last_date = value;
				this.SendPropertyChanged("last_date");
				this.Onlast_dateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
