<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="gallaryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.gallery" Member="galleries">
    <Type Name="gallery">
      <Column Name="gid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="proid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gallfimg" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gallbimg" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gallrimg" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="galllimg" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>