#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class productDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertproduct(product instance);
  partial void Updateproduct(product instance);
  partial void Deleteproduct(product instance);
  #endregion
	
	public productDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public productDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public productDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public productDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public productDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<product> products
	{
		get
		{
			return this.GetTable<product>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _proid;
	
	private System.Nullable<int> _subcatid;
	
	private string _proname;
	
	private string _prodec;
	
	private string _proimg;
	
	private string _probimg;
	
	private System.Nullable<int> _proprice;
	
	private System.Nullable<int> _proofferprice;
	
	private System.Nullable<int> _status;
	
	private System.Nullable<int> _category;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnproidChanging(int value);
    partial void OnproidChanged();
    partial void OnsubcatidChanging(System.Nullable<int> value);
    partial void OnsubcatidChanged();
    partial void OnpronameChanging(string value);
    partial void OnpronameChanged();
    partial void OnprodecChanging(string value);
    partial void OnprodecChanged();
    partial void OnproimgChanging(string value);
    partial void OnproimgChanged();
    partial void OnprobimgChanging(string value);
    partial void OnprobimgChanged();
    partial void OnpropriceChanging(System.Nullable<int> value);
    partial void OnpropriceChanged();
    partial void OnproofferpriceChanging(System.Nullable<int> value);
    partial void OnproofferpriceChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OncategoryChanging(System.Nullable<int> value);
    partial void OncategoryChanged();
    #endregion
	
	public product()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int proid
	{
		get
		{
			return this._proid;
		}
		set
		{
			if ((this._proid != value))
			{
				this.OnproidChanging(value);
				this.SendPropertyChanging();
				this._proid = value;
				this.SendPropertyChanged("proid");
				this.OnproidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subcatid", DbType="Int")]
	public System.Nullable<int> subcatid
	{
		get
		{
			return this._subcatid;
		}
		set
		{
			if ((this._subcatid != value))
			{
				this.OnsubcatidChanging(value);
				this.SendPropertyChanging();
				this._subcatid = value;
				this.SendPropertyChanged("subcatid");
				this.OnsubcatidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proname", DbType="NVarChar(50)")]
	public string proname
	{
		get
		{
			return this._proname;
		}
		set
		{
			if ((this._proname != value))
			{
				this.OnpronameChanging(value);
				this.SendPropertyChanging();
				this._proname = value;
				this.SendPropertyChanged("proname");
				this.OnpronameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prodec", DbType="NVarChar(50)")]
	public string prodec
	{
		get
		{
			return this._prodec;
		}
		set
		{
			if ((this._prodec != value))
			{
				this.OnprodecChanging(value);
				this.SendPropertyChanging();
				this._prodec = value;
				this.SendPropertyChanged("prodec");
				this.OnprodecChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proimg", DbType="NVarChar(50)")]
	public string proimg
	{
		get
		{
			return this._proimg;
		}
		set
		{
			if ((this._proimg != value))
			{
				this.OnproimgChanging(value);
				this.SendPropertyChanging();
				this._proimg = value;
				this.SendPropertyChanged("proimg");
				this.OnproimgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_probimg", DbType="NVarChar(50)")]
	public string probimg
	{
		get
		{
			return this._probimg;
		}
		set
		{
			if ((this._probimg != value))
			{
				this.OnprobimgChanging(value);
				this.SendPropertyChanging();
				this._probimg = value;
				this.SendPropertyChanged("probimg");
				this.OnprobimgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proprice", DbType="Int")]
	public System.Nullable<int> proprice
	{
		get
		{
			return this._proprice;
		}
		set
		{
			if ((this._proprice != value))
			{
				this.OnpropriceChanging(value);
				this.SendPropertyChanging();
				this._proprice = value;
				this.SendPropertyChanged("proprice");
				this.OnpropriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proofferprice", DbType="Int")]
	public System.Nullable<int> proofferprice
	{
		get
		{
			return this._proofferprice;
		}
		set
		{
			if ((this._proofferprice != value))
			{
				this.OnproofferpriceChanging(value);
				this.SendPropertyChanging();
				this._proofferprice = value;
				this.SendPropertyChanged("proofferprice");
				this.OnproofferpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
	public System.Nullable<int> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="Int")]
	public System.Nullable<int> category
	{
		get
		{
			return this._category;
		}
		set
		{
			if ((this._category != value))
			{
				this.OncategoryChanging(value);
				this.SendPropertyChanging();
				this._category = value;
				this.SendPropertyChanged("category");
				this.OncategoryChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
