#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class ratingDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertrating(rating instance);
  partial void Updaterating(rating instance);
  partial void Deleterating(rating instance);
  #endregion
	
	public ratingDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ratingDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ratingDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ratingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ratingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<rating> ratings
	{
		get
		{
			return this.GetTable<rating>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rating")]
public partial class rating : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _rid;
	
	private System.Nullable<decimal> _umobileno;
	
	private string _name;
	
	private string _eid;
	
	private string _rate;
	
	private string _rmsg;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnridChanging(int value);
    partial void OnridChanged();
    partial void OnumobilenoChanging(System.Nullable<decimal> value);
    partial void OnumobilenoChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OneidChanging(string value);
    partial void OneidChanged();
    partial void OnrateChanging(string value);
    partial void OnrateChanged();
    partial void OnrmsgChanging(string value);
    partial void OnrmsgChanged();
    #endregion
	
	public rating()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int rid
	{
		get
		{
			return this._rid;
		}
		set
		{
			if ((this._rid != value))
			{
				this.OnridChanging(value);
				this.SendPropertyChanging();
				this._rid = value;
				this.SendPropertyChanged("rid");
				this.OnridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_umobileno", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> umobileno
	{
		get
		{
			return this._umobileno;
		}
		set
		{
			if ((this._umobileno != value))
			{
				this.OnumobilenoChanging(value);
				this.SendPropertyChanging();
				this._umobileno = value;
				this.SendPropertyChanged("umobileno");
				this.OnumobilenoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", DbType="NVarChar(50)")]
	public string eid
	{
		get
		{
			return this._eid;
		}
		set
		{
			if ((this._eid != value))
			{
				this.OneidChanging(value);
				this.SendPropertyChanging();
				this._eid = value;
				this.SendPropertyChanged("eid");
				this.OneidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NVarChar(50)")]
	public string rate
	{
		get
		{
			return this._rate;
		}
		set
		{
			if ((this._rate != value))
			{
				this.OnrateChanging(value);
				this.SendPropertyChanging();
				this._rate = value;
				this.SendPropertyChanged("rate");
				this.OnrateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rmsg", DbType="NVarChar(50)")]
	public string rmsg
	{
		get
		{
			return this._rmsg;
		}
		set
		{
			if ((this._rmsg != value))
			{
				this.OnrmsgChanging(value);
				this.SendPropertyChanging();
				this._rmsg = value;
				this.SendPropertyChanged("rmsg");
				this.OnrmsgChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
