<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="subcategoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.subcategory" Member="subcategories">
    <Type Name="subcategory">
      <Column Name="subcatid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="catid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subcatname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="subdec" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>